spring:
  application:
    name: config-client
  cloud:
    config:
      label: master
      profile: dev
      uri: http://localhost:8767
  rabbitmq:
    host: 172.16.128.35
    port: 5672
    username: mall
    password: mall
    virtual-host: mall
  zipkin:
    base-url: http://172.16.128.35:9411
    sender:
      type: web
#
server:
  port: 8765

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
# Spring Cloud D版本以后，feign默认依赖的hystrix默认未启用。
feign:
  hystrix:
    enabled: true

dfz:
  foo: NAN

management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
