spring:
  application:
    name: config-client
  cloud:
    config:
      label: master
      profile: dev
      uri: http://localhost:8767
  rabbitmq:
    host: 172.16.128.35
    port: 5672
    username: mall
    password: mall
    virtual-host: mall
  zipkin:
    base-url: http://172.16.128.35:9411
    sender:
      type: web

SERVICE-CONSUMER:
  token: abc
#
server:
  port: 8765
SERVICE-PROVIDER:
  ribbon:
    MaxAutoRetries: 2
    MaxAutoRetriesNextServer: 22
    ConnectTimeout: 222
    ReadTimeout: 2222

ribbon:
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 11
  ConnectTimeout: 111
  ReadTimeout: 1111

feign:
#  client:
#    config:
#      default:
#        connectTimeout: 3
#        readTimeout: 33
#      SERVICE-PROVIDER:
#        connectTimeout: 4
#        readTimeout: 44
  okhttp:
    enabled: true
  hystrix:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
# Spring Cloud D版本以后，feign默认依赖的hystrix默认未启用。
#feign:
#  hystrix:
#    enabled: false
hystrix:
  propagate:
    request-attribute:
      enabled: true

dfz:
  foo: NAN

management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
