spring:
  application:
    name: service-provider
  zipkin:
    base-url: http://172.16.128.35:9411

server:
  port: 8763

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

