spring:
  application:
    name: service-provider
  zipkin:
    base-url: http://172.16.128.35:9411

server:
  port: 8763

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

