spring:
  application:
    name: service-consumer
  zipkin:
    base-url: http://172.16.128.35:9411

server:
  port: 8764

management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

